// console.log("Anjali");
// console.log("Anjali");
// console.log("Anjali");
// console.log("IloveJavascript");
fullname="Anjali";
console.log("fullname");
 let age=23;
x=null;
y=undefined;
isfollow=false;
let name="tony";
let totalprice=1000;
var agee=35;
var agee=46;
var agee=45;
console.log("y");
console.log("x");
console.log("isfollow");
console.log(name);
console.log(totalprice);
console.log("agee");